name: Build, test and package

on: push

env:
  MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
  ACCEPT_EULA: "Y"
  MSSQL_PID: "developer"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  
jobs:
  package:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: HicServices/RDMP
          ref: develop
          path: RDMP
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Get version
        id: version
        shell: cmd
        run: |
          getversions >> %GITHUB_OUTPUT%
      - name: Set up database
        run: |
          dotnet run --project RDMP/Tools/rdmp/rdmp.csproj -c Release -- install localhost TEST_ -d
      - name: Test
        run: |
          dotnet test
      - name: Build
        run: |
          @"
          <?xml version="1.0" encoding="utf-8"?>
          <package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
              <metadata>
                  <id>HIC.Extensions</id>
                  <version>${{ steps.version.outputs.version }}</version>
                  <authors>Health Informatics Service, University of Dundee</authors>
                  <description>Imaging plugin for Research Data Management Platform </description>
                  <dependencies>
                      <dependency id="HIC.RDMP.Plugin" version="${{ steps.version.outputs.rdmpversion }}" />
                  </dependencies>
              </metadata>
          </package>
          "@ | Out-File -Encoding ASCII plugin.nuspec

          dotnet publish -p:DebugType=embedded -p:GenerateDocumentation=false Plugin/windows/windows.csproj -c Release -o p/windows
          dotnet publish -p:DebugType=embedded -p:GenerateDocumentation=false Plugin/main/main.csproj -c Release -o p/main
          rm p/windows/windows.dll
          rm p/main/main.dll
          cmd /c 7z a -tzip HIC.Rdmp.Extensions.Plugin.${{ steps.version.outputs.version }}.nupkg plugin.nuspec p
          dotnet run --project RDMP/Tools/rdmp/rdmp.csproj -c Release -- pack -p --file HIC.Rdmp.Extensions.Plugin.${{ steps.version.outputs.version }}.nupkg --dir yaml
          dotnet run --project RDMP/Tools/rdmp/rdmp.csproj -c Release -- cmd listsupportedcommands --dir yaml
      - name: Store created nupkg files
        uses: actions/upload-artifact@v3
        with:
          path: ./*.nupkg
          retention-days: 1
      - name: Upload release binaries
        if: contains(github.ref,'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: 'HIC.Rdmp.Extensions.Plugin.${{ steps.version.outputs.version }}.nupkg'
